# -*- coding: utf-8 -*-
{
    'name': "Emisión de Facturas Electrónicas",
    'summary': "Integracion con API para envio de comprobantes.",
    'description': """
    """,
    'author': "Facturación VIP",
    'website': "http://facturacion.vip",
    'category': 'invoicing',
    'version': '0.1',
    'depends': ['base','base_setup','sale','product','stock','sale_stock','sale_margin',
                'account','account_cancel','l10n_pe','odoope_einvoice_base','odoope_toponyms',
                'sunat_get_data'],
    'data': [
        # 'security/ir.model.access.csv',
        'template_mail/mail_invoice.xml',
        'config/res_config_settings.xml',
        'data/product_uom.xml',
        'data/account_journal.xml',
        'data/account_tax_group.xml',
        'data/res_currency.xml',
        'data/res_lang_pe.xml',
        'data/ir_mail_server.xml',
        'data/report_url.xml',
        'data/modalidad_transporte.xml',
        'data/motivo_traslado.xml',
        'cron/validez_comprobante_cron.xml',
        'cron/guia_remision_cron.xml',
        'cron/account_invoice_cron.xml',
        'cron/account_summary_cron.xml',
        'views/company/view_company.xml',
        'views/account/view_account_log_status.xml',
        'views/partner/view_res_partner.xml',
        'views/product/view_product_uom.xml',
        'views/account/view_account_journal.xml',
        'views/account/view_acc_inv_boleta.xml',
        'views/account/view_acc_inv_factura.xml',
        'views/account/view_acc_inv_nota_credito.xml',
        'views/account/view_acc_inv_nota_debito.xml',
        'views/account/view_acc_summary.xml',
        'views/account/view_acc_log_status.xml',
        'views/account/view_filter_invoice.xml',
        'views/account/view_acc_mis_comprobantes.xml',
        'views/sale_order/sale_order.xml',
        'views/account/view_account_invoice.xml',
        'views/account/view_account_tax.xml',
        'views/account/view_acc_com_baja.xml',
        'views/stock/stock_picking.xml',
        'views/stock/stock_records.xml',
        'views/stock/stock_view.xml',
        'views/guia_remision/popup_form_seleccion_ubigeo.xml',
        'views/guia_remision/res_partner_destinatario.xml',
        'views/guia_remision/view_transporte.xml',
        'views/guia_remision/guia_remision_electronica.xml',
        'views/guia_remision/view_catalogo_motivo_traslado.xml',
        'views/guia_remision/menu.xml',
        'reports/report_guia_remision.xml',
        'security/res_groups.xml',  
        'security/res_groups_stock.xml',
        'action_server/nuevo_campo_tipo_doc.xml'
    ],
    'external_dependencies':{"python":["jwt"]},
    'demo': [
    ],
}