version: '2'
services:
  db:
    container_name: ${CONTAINER_DB}
    image: postgres:10-alpine
    restart: always
    environment:
      # - TZ=America/Lima
      # - PGTZ=America/Lima
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - VOLUME_DB:/var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
  web:
    container_name: ${CONTAINER_ODOO}
    image: efact_odoo:11
    build: ./docker
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev all"
    depends_on:
      - db
    ports:
      - ${PORT}:8069
      - ${CHAT_PORT}:8072
    volumes:
      - VOLUME_ODOO:/var/lib/odoo
      - ./docker:/etc/odoo/
      - ./../addons:/mnt/extra-addons
      - ./../addons-facturacion-vip:/mnt/extra-addons-facturacion-vip
      - ./../addons-clarico:/mnt/extra-addons-clarico
      - ./../addons-adaptiv:/mnt/extra-addons-adaptiv
      - ./../addons-private:/mnt/extra-addons-private
      - ./../addons-customize:/mnt/extra-addons-customize
      - ./../addons-openeducat:/mnt/extra-addons-openeducat
volumes:
  VOLUME_ODOO:
  VOLUME_DB:
